### ISSUE TITLE
rxjs before zen-observable?

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/any-observable#1]
It's got way more methods, lots more features. It seems to be the `bluebird` of observables (not sure on performance).

**Comment by sindresorhus** [comment]
`zen-observable` is a plain polyfill, so thought that should take priority. Happy to change though.

**Comment by jamestalmage** [comment]
See https://github.com/ReactiveX/rxjs/tree/master/src/add/observable

It could go either way really. If both libraries are available and `any-observable` causes `rxjs` to load unnecessarily, then you've wasted cycles loading the larger library. But if it is there, it seems likely it's the one you want.

I guess it comes down to, would you prefer `any-promise` load `bluebird` or `pinkie`? If you have `bluebird` installed, then almost always `bluebird`, right?

Counterpoint: If you expect to be able to use all the extra goodies `rxjs` provides, you probably should be explicitly registering it anyways.

**Comment by sindresorhus** [comment]
Good point.
