### ISSUE TITLE
Released version is missing files

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/any-observable#15]
I tried to use `any-observable` but received the error

> Error: Cannot find module './register'

Dived into the code and it looks like the version that is being released on `npm` has the following `files` property specified.

``` json
  "files": [
    "index.js"
  ]
```

Is it possible to do a new released in between to fix that?

**Comment by sindresorhus** [comment]
Done. 0.2.0 published.

**Comment by SamVerschueren** [comment]
Thanks Sindre!
