### ISSUE TITLE
Doesn't seem to work with RxJS 6

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/any-observable#18]
Is it possible that the auto detect feature doesn't work for RxJS 6? Might have to pull in @benlesh here because I'm not sure what all the changes are in this new version.

So we try to load in `rxjs/Observable` right [here](https://github.com/sindresorhus/any-observable/blob/master/register.js#L41). But it looks like that doesn't exist anymore and you need to import directly from `rxjs` instead.

So we can easily fix this by adding `rxjs` to the `libs` list as the last element in order to support RxJS 6. But before I do a PR, I need to be sure that my findings are correct.

**Comment by brandonroberts** [comment]
@SamVerschueren Your finding is correct that for RxJS 6, the `Observable` import should come from `rxjs`. If the consumer has the `rxjs-compat` package installed also, either import path will work with version 6.

**Comment by benlesh** [comment]
This is likely because import locations changed with RxJS 6. It's hard to say, because I don't have time to dig into it.
