### ISSUE TITLE
Shortcut registrations?

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/any-observable#2]
I like that you can pick your desired registration. That's awesome. I never stopped to look at `any-promise` before. I dig it.

What about providing a list of shortcut registrations so you can do this:

```
ava --require=any-observable/register/zen
ava --require=any-observable/register/rxjs-minimal
ava --require=any-observable/register/rxjs-all
```

Keep them in a `registration` subfolder so they don't clutter up the main code base, and you can be pretty liberal about accepting PR's with registration shortcuts as new implementations become available.

**Comment by sindresorhus** [comment]
👍 Good idea. Maybe `rxjs-minimal` → `rxjs`.
