### ISSUE TITLE
Just use rxjs-minimal instead of both rxjs-full and minimal

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/any-observable#3]
See [this comment](https://github.com/sindresorhus/any-observable/commit/33293a53fb7b242aa61c42ea036db5bd849ababf#commitcomment-17275070).

RxJs uses an interesting loader mechanism that allows users to specify exactly which Observable methods are implemented. This allows them to pursue a robust API, and users don't necessarily have to pay the price with larger browserified packages. (I think you can accomplish similar with bluebird, but it requires a build step - rxjs automates feature selection via require/import statements - it's pretty cool). More details [here](http://reactivex.io/rxjs/manual/installation.html)

Anyways. I think we should probably just select the minimal install when auto-resolving. Then users can patch to get the features they want, but we aren't necessarily loading the entirety of rxjs.

**Comment by sindresorhus** [comment]
Agreed.

Just need to make sure to document how to get the full one:

> Might be worth explaining that in the docs here, even though it's an rxjs implementation detail. Especially if we default to the minimal one over the full one. - https://github.com/sindresorhus/any-observable/commit/33293a53fb7b242aa61c42ea036db5bd849ababf#commitcomment-17275070
