### ISSUE TITLE
Allow for different export patterns.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/any-observable#7]
The string only option does not fit RxJs.

You can't do:

``` js
require('rxjs/Observable');
```

You need to do:

``` js
require('rxjs/Observable').Observable;
```

I think our default lookup strategy should be something like this:

``` js
function load(name) {
  var loaded = require(name);
  return loaded.Observable || loaded.default || loaded;
}
```

**Comment by sindresorhus** [comment]
We already manually handle that for RxJS, but yeah, might be useful for other future libs.

**Comment by jamestalmage** [comment]
No, we only do that in the `detect()` function. That won't work if they call `register('rxjs')`
